version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:20.0
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Start application
          command: npm start

workflows:
  version: 2
  build_and_test:
    jobs:
      - build


